baseURL = "https://the.b1h.space"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "the B1H space"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

#date format
dateFormat = "01/02/2006"

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
#  [[menu.main]]
#    identifier = "tags"
#    pre = ""
#    post = ""
#    name = "Tags"
#    url = "/tags/"
#    title = ""
#    weight = 2
#  [[menu.main]]
#    identifier = "categories"
#    pre = ""
#    post = ""
#    name = "Categories"
#    url = "/categories/"
#    title = ""
#    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true

# Footer config
  [params.footer]
    enable = true
    custom = 'Bill He 2019-2020'
    hugo = false
    copyright = false
    author = false
    since = 2019

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
